inherit_from: .rubocop_todo.yml

require:
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Layout/LineLength:
  Max: 128

Layout/MultilineMethodCallIndentation:
  Enabled: false
